// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVofvxuExotOO1JxidV0SFRw50H-efhhM',
    appId: '1:757218420804:web:ffc35efe53aabea2aff411',
    messagingSenderId: '757218420804',
    projectId: 'absence-d1e8f',
    authDomain: 'absence-d1e8f.firebaseapp.com',
    storageBucket: 'absence-d1e8f.firebasestorage.app',
    measurementId: 'G-TY6NBT4D9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA_5Hc1PtA8atbbNdqp6IqZhQJ_OmE_q8',
    appId: '1:757218420804:android:9be87c6e7841cbd2aff411',
    messagingSenderId: '757218420804',
    projectId: 'absence-d1e8f',
    storageBucket: 'absence-d1e8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1USxxhpQhyv0y_76diabbzEAya6KMuA',
    appId: '1:757218420804:ios:87fb88fde3211a53aff411',
    messagingSenderId: '757218420804',
    projectId: 'absence-d1e8f',
    storageBucket: 'absence-d1e8f.firebasestorage.app',
    iosBundleId: 'com.example.absence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVofvxuExotOO1JxidV0SFRw50H-efhhM',
    appId: '1:757218420804:web:25cc7e7824340b5caff411',
    messagingSenderId: '757218420804',
    projectId: 'absence-d1e8f',
    authDomain: 'absence-d1e8f.firebaseapp.com',
    storageBucket: 'absence-d1e8f.firebasestorage.app',
    measurementId: 'G-HR4ZKM9FB5',
  );
}
